### ISSUE TITLE
Completely wrong code!

### ISSUE THREAD

**Issue by Elmue** [awakecoding/Win32Keyboard#1]
You code is full of bugs and the code is not finished.

Your code for pVkToWcharTable shows COMPLETE GARBAGE.
Your code does not decode the deadkeys. Quite useless.
And for the tables E0 and E1 your code runs over the end of the table and shows any memory contents as if it were from the table which is GARBAGE.

You surely do not have enough programming skills to write this code which admittedly is difficult due to a lack of documentation. An experienced programmer is required here who has the skills to do reverse engineering.

Did you ever test you code before uploading it ?
Did you not notice that your code prints garbage ?
Or don't you care and think you are cool when you fill Github with not working code ?

Either you finish a project and make sure that it works.
Or you do NOT upload it to Github.

Your project is not useful for ANYBODY.

**Comment by awakecoding** [comment]
In case you hadn't noticed, this relatively small code sample hasn't seen an update in over 10 years, and the last time I have used it, it worked just fine. It definitely has some flaws, just like pretty much everything you will find on GitHub. 

I've written this tool a long time ago to help debug which scancodes were received inside an RDP session from mstsc, to help figure out what FreeRDP should send. The same tool has been useful to many other people over the years for similar use cases.

This code is provided as-is, with no guarantees of any kind. The only garbage here is your unwarranted comment, not some 10-year old experimental tool that worked for what I needed it for.

This is one of my many personal GitHub repositories, and I have tons of similar experimental stuff. If you don't like it, then kindly go bother someone else.

**Comment by edwardskrod** [comment]
> You code is full of bugs and the code is not finished.
> 
> Your code for pVkToWcharTable shows COMPLETE GARBAGE. Your code does not decode the deadkeys. Quite useless. And for the tables E0 and E1 your code runs over the end of the table and shows any memory contents as if it were from the table which is GARBAGE.
> 
> You surely do not have enough programming skills to write this code which admittedly is difficult due to a lack of documentation. An experienced programmer is required here who has the skills to do reverse engineering.
> 
> Did you ever test you code before uploading it ? Did you not notice that your code prints garbage ? Or don't you care and think you are cool when you fill Github with not working code ?
> 
> Either you finish a project and make sure that it works. Or you do NOT upload it to Github.
> 
> Your project is not useful for ANYBODY.

This is an incredibly inappropriate thing to write to someone who has shared their project with the world on GitHub.

ProTip:  Don't be this person.

**Comment by rweichler** [comment]
I 100% agree with @Elmue, this repository should be deleted from Github.

**Comment by guywaldman** [comment]
@Elmue @rweichler Frankly, this is unacceptable behavior in the open-source community.
There's no excuse for replying in this manner in a 10-year old repository and in my opinion, this would even be unacceptable for a very up-to-date and popular repository.

If you have improvements in mind for any project on GitHub, I suggest that you do one of the following (or combination thereof):

1. Open an issue, phrased in a **respectable** manner.
2. Contribute to the project yourself.
3. Donate/sponsor the maintainer to support their work and incentivize ongoing contributions to the project.

I sincerely hope that you reconsider.

**Comment by Streq** [comment]
@Elmue 
> Either you finish a project and make sure that it works. Or you do NOT upload it to Github.
> 
> Your project is not useful for ANYBODY.

Not only is this a wrong and naive view of the purpose of Github, which is arguably at its most useful when the project in question isn't finished, but it also conveys a wrong and entitled way of seeing OSS.

The onus is on **you** to find (or provide) code that **you** find useful, not on the maintainers/creators, they have no obligation, moral or otherwise, to even upload code that is working or useful to anybody whatsoever.

You can try paying someone for their work if you want better results.

Cheers!
